<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Requests\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\My Libraries\FabToolKit\FabToolKit\FabToolKit.csproj" />
  </ItemGroup>

</Project>